# LAB 4: NEURAL NETWORK

In this lab, we will explore Neural Networks, which can be trained using the Gradient Descent algorithm.

Specifically, we will cover the following topics:

- A brief introduction to the PyTorch library for implementing Neural Networks.

- Implementation of a neural network using PyTorch.

- Discussion on overfitting.

**A neuron is like a function; it takes a few inputs and calculates an output. Its adjusts its parameters (training), using the gradient descent method to minimise a loss function**.


The circle below illustrates an artificial neuron.

<figure>
  <img style="float: left;" src="../../fig/NN1.png" width="800"/>
</figure>

At the far left we see two input values plus a bias value. The input values are 1 and 0 (the green numbers), while the bias holds a value of -2 (the brown number).

The two inputs are then multiplied by their  weights, which are 7 and 3 (the blue numbers).

Finally we add it up with the bias and end up with a number, in this case: 5 (the red number). This is the input for our artificial neuron.

The neuron then performs some kind of computation on this number using activation function ( in our case the Sigmoid function), and then spits out an output. This happens to be 1, as Sigmoid of 5 equals to 1, if we round the number up (more about activation function down).

You can find more explanation about the structure [here](https://www.leewayhertz.com/what-are-neural-networks/#What-are-neural-networks)

# Single layer network : Perceptron

The perceptron algorithm was one of the first algorithms used to implement a simple neural network.

Perceptrons are supervised learning algorithms and is a type of an ANN

Let's remind th components of a Perceptron:
    
- Inputs: The perceptron takes several inputs $(x_1,x_2,…,x_n)$


- Weights: Each input is associated with a weight $(w_1,w_2,…,w_n).$

- Bias: A bias term $(b or w_0)$ is added to shift the decision boundary.

- Activation Function: The perceptron uses a step function (a simple thresholding function) to determine whether the weighted sum of inputs plus the bias is above or below a certain threshold.

- Binary Output: The output of a perceptron is binary (-1 or 1 that can be easily switched to 0 or 1), making it suitable for linearly separable classification problems.

### Limitations of Perceptron:

- Linear separability: The perceptron can only solve problems that are linearly separable (i.e., it can only classify data that can be separated by a straight line or hyperplane). It cannot solve more complex problems like XOR.

- Single-layer model: The original perceptron is a single-layer model and does not have hidden layers, limiting its expressiveness.

.

<figure>
  <img style="float: left;" src="../../fig/perceptron.png" width="800"/>
</figure>

# Activation Functions

Activation functions play an integral role in neural networks by introducing non-linearity.
This non-linearity allows neural networks to develop complex representations and functions based on the inputs that would not be possible with a simple linear layers.

You can find all types of activation functions [here](https://www.shiksha.com/online-courses/articles/activation-functions-with-real-life-analogy-and-python-code/)

Unlike the perceptron, which uses a simple step function for activation, neurons in modern neural networks can use a variety of activation functions, such as:

<figure>
  <img style="float: left;" src="../../fig/activation_function.png" width="800"/>
</figure>

# Multi-layer Networks

Multi-layer Networks: Neurons are part of more sophisticated architectures called multi-layer perceptrons (MLPs) or deep neural networks, where neurons are organized into layers (input layer, hidden layers, and output layer). Each layer performs computations, and the output of one layer is fed as input to the next.

<figure>
  <img style="float: left;" src="../../fig/MLP.png" width="800"/>
</figure>

Each hidden/output node is now related to all the nodes of the previous layer: we say that the network is fully connected.


###  Inputs to the 2nd Hidden Layer
The inputs to a neuron in the 2nd hidden layer come from the outputs of the neurons in the 1st hidden layer.

Here we have:
- $ h_1^1, h_1^2, h_1^3,h_1^4 $ represent the activations (outputs) of the neurons in the **1st hidden layer**. These are the inputs to the neurons in the 2nd hidden layer.
.

- Let's assume that $ w_{ij}^{(3)} $ represent the weights connecting neuron $ i $ in the 1st hidden layer to neuron $ j $ in the 2nd hidden layer.
.

- $ b_j^{2} $ is the bias for neuron $ j $ in the 2nd hidden layer.



### Weighted Sum for a Neuron in the 2nd Hidden Layer
The value of the weighted sum for neuron $ j $ in the 2nd hidden layer is:

$$
a_j^{2} = \sum_{i=1}^{4} w_{ij}^{2} h_i^{1} + b_j^{2}
$$


After computing the weighted sum $a_j^{2}$, we apply an activation function $ f(a_j^{2}) $ to compute the final output (activation) of the neuron. 


So the output (activation) of neuron $ j $ in the 2nd hidden layer is:


$$
h_j^{2} = f\left(\sum_{i=1}^{4} w_{ij}^{2} h_i^{1} + b_j^{2} \right)
$$



If we are using an activation function like ReLU, sigmoid, or tanh, the output of neuron $ j $ in the 2nd hidden layer would be:

- **Sigmoid**:
  $$
  h_j^{2} = \frac{1}{1 + e^{-a_j^{2}}}
  $$
- **ReLU**:
  $$
 h_j^{2} = \max(0, a_j^{2})
  $$
- **Tanh**:
  $$
 h_j^{2} = \tanh(a_j^{2}) = \frac{e^{a_j^{2}} - e^{-a_j^{2}}}{e^{a_j^{2}} + e^{-a_j^{2}}}
  $$

#  Training the Neural Network

To train a NN, we need to follow those process: 

- Forward pass: Compute the outputs.

- Compute loss: Compare outputs with actual labels.

- Backward pass: Compute gradients of loss with respect to weights and bias.

- Optimize: Update weights using the optimizer (e.g., Adam, SGD).

- Repeat for many epochs, using batches of data.

### Forward pass 

The action of obtaining the output y from the input x is called a forward pass.

In the forward pass, the input values are multiplied by the weights, biases are added, and the result is passed through an activation function. This process is repeated for every layer, eventually yielding the output of the network.

We can implement the forward pass of our multi-layer perceptron in a few lines. We use random weights and bias for the example:

In [1]:
import numpy as np

sizes = [3, 4, 3, 1]  # number of neurons in each layer
num_layers = len(sizes)  # one input layer, 2 hidden layers and one output layer

# the first layer does not have bias as it's the input layer
biases = [np.random.randn(sizes[i], 1) for i in range(1, num_layers)]

# we use the transpose of the weight matrices cause we need the same size as the bias vector
weights = [np.random.randn(sizes[i], sizes[i-1]) for i in range(1, num_layers)]

In [2]:
weights

[array([[ 1.07763987,  1.3355706 , -1.43261954],
        [-0.09855782,  1.2955058 ,  0.72416075],
        [ 0.10502936, -1.67961677,  1.40173685],
        [-0.04502352,  1.08057925, -1.03064786]]),
 array([[ 0.04128528,  0.06089792, -0.6319817 ,  1.06822963],
        [ 0.15103529, -0.29569492, -1.13376815,  1.00328582],
        [ 0.1006686 , -1.52056104,  1.06255129,  1.87065629]]),
 array([[0.59044125, 2.16752136, 0.10428971]])]

Once we have initialized the network size and its parameters, we are ready to implement the forward pass. We can then feed the network with any arbitrary input.

In [3]:
# Define an activation function
def g(z):
    """Sigmoid function."""
    return 1.0/(1.0 + np.exp(-z)) 

# define output/input relation for a MLP
def network_forward(h): 
    """Return the output of the network given input h."""
    for b, w in zip(biases, weights):
        z = np.dot(w, h) + b # mat-vect product + bias
        h = g(z) # apply activation function
    return h

# Example input
input = np.array([[1.],[2.],[3.]]) # a column vector (1,2,3)^T
output = network_forward(input)
print(output)

[[0.60611854]]

### Compute the Loss/Cost function:

The loss function measures how far off the network’s predictions are from the true labels.
Some common loss functions are:

- Mean Squared Error (MSE) for regression tasks.

- Cross-Entropy Loss for classification tasks (either binary or multi-class)

In [4]:
def binary_cross_entropy_loss(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

### Backward Pass (Backpropagation):

The backward pass involves calculating the gradients of the loss with respect to the weights and biases in each layer.

The gradients are then used to update the weights and biases to minimize the loss (i.e., make the model’s predictions more accurate).

This process is called backpropagation cause it uses the chain rule from calculus to compute the gradients layer by layer, starting from the output layer and moving backward through the network

.

<figure>
  <img style="float: left;" src="../../fig/bp.png" width="800"/>
</figure>

# Let's try with a real dataset

In [2]:
import pandas as pd
import numpy as np

df=  pd.read_csv("Intro to ML Class data.csv")
df

,Acronym,Sleep Time,Wake Time,Smoking (#e),Screen Time (hrs),Conintuous Sleep?
0,CD,21:00,05:00,0.0,8.0,N
1,LJ,00:30,06:53,25.0,6.0,Y
2,DB,00:00,06:00,0.0,5.0,Y
3,DC,23:00,07:00,0.0,10.0,Y
4,HD,23:00,06:30,0.0,5.0,Y
5,NN,23:00,08:00,0.0,4.5,N
6,ML,22:00,07:00,0.0,10.0,N
7,CC,00:30,07:30,0.0,10.0,Y
8,MM,00:00,12:00,0.0,10.0,Y
9,HN,23:00,06:30,0.0,12.0,Y
10,YH,22:45,07:30,0.0,2.5,N
11,CR,00:00,06:00,0.0,6.0,N
12,KL,01:00,06:30,0.0,9.0,Y
13,KK,01:00,07:30,0.0,9.0,Y
14,JW,23:00,08:00,0.0,10.0,Y
15,EI,03:00,07:15,0.0,8.0,Y
16,EI,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN
18,AA,04:00,07:30,0.0,5.0,Y
19,NaN,NaN,NaN,NaN,NaN,NaN
20,GM,01:10,09:20,0.0,3.5,Y

## Basic data preprocessing as we did for the last assignment

In [3]:

# First, we rename the columns for convenience.
rename_dict = {
    'Sleep Time': 'sleep_time',
    'Wake Time': 'wake_time',
    'Smoking (#e)': 'smoking',
    'Screen Time (hrs)': 'screen_time',
    'Conintuous Sleep?': 'continuous_sleep'}
df.rename(columns=rename_dict, inplace=True)

# relabel the two classes as 0 and 1
df['continuous_sleep'] = df['continuous_sleep'].map({'N': 0, 'Y': 1})

# Clean up missing target values
df['continuous_sleep'] = pd.to_numeric(df['continuous_sleep'], errors='coerce')
df = df.dropna(subset=['continuous_sleep']).reset_index(drop=True)
df['continuous_sleep'] = df['continuous_sleep'].astype(int)

df['smoking'] = pd.to_numeric(df['smoking'], errors='coerce')
df['smoking'] = df['smoking'].astype(int)

# Convert the column to float
df['screen_time'] = df['screen_time'].astype(float)

#  Convert columns to datetime first (just in case they are stored as strings)
df['sleep_time'] = pd.to_datetime(df['sleep_time'], format='%H:%M', errors='coerce')
df['wake_time'] = pd.to_datetime(df['wake_time'], format='%H:%M', errors='coerce')


#  Extract continuous numeric features (hours) for KNN distance metrics
df['sleep_time'] = df['sleep_time'].dt.hour + df['sleep_time'].dt.minute / 60.0
df['wake_time'] = df['wake_time'].dt.hour + df['wake_time'].dt.minute / 60.0

# Treat 00:xx as 24:xx
df.loc[df['sleep_time'] < 1, 'sleep_time'] += 24
df.loc[df['wake_time'] < 1, 'wake_time'] += 24

# Round to 1 decimals
df['sleep_time'] = df['sleep_time'].round(1)
df['wake_time'] = df['wake_time'].round(1)

In [4]:
df

   Acronym  sleep_time  wake_time  smoking  screen_time  continuous_sleep
0       CD        21.0        5.0        0          8.0                 0
1       LJ        24.5        6.9       25          6.0                 1
2       DB        24.0        6.0        0          5.0                 1
3       DC        23.0        7.0        0         10.0                 1
4       HD        23.0        6.5        0          5.0                 1
5       NN        23.0        8.0        0          4.5                 0
6       ML        22.0        7.0        0         10.0                 0
7       CC        24.5        7.5        0         10.0                 1
8       MM        24.0       12.0        0         10.0                 1
9       HN        23.0        6.5        0         12.0                 1
10      YH        22.8        7.5        0          2.5                 0
11      CR        24.0        6.0        0          6.0                 0
12      KL         1.0        6.5        0          9.0                 1
13      KK         1.0        7.5        0          9.0                 1
14      JW        23.0        8.0        0         10.0                 1
15      EI         3.0        7.2        0          8.0                 1
16      AA         4.0        7.5        0          5.0                 1
17      GM         1.2        9.3        0          3.5                 1